Vault
PoCInnovation/SecureEnv pull request #29
Opened 2023-06-07 14:08 UTC by adamdeziri

# Description

Dockerization of HashiCorp's Vault for production purposes with HTTPS handling.
This Vault Docker image is meant to be used with secure-env.

# Changes include

- [ ] Bugfix (non-breaking change that solves an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (change that is not backwards-compatible and/or changes current functionality)

# Checklist

- [x] I have assigned this PR to myself
- [x] I have added at least 1 reviewer
- [x] I have added the needed labels
- [ ] I have linked this PR to an issue
- [x] I have linked this PR to a milestone
- [x] I have linked this PR to a project
- [x] I have tested this code
- [ ] I have added / updated tests (unit / functional / end-to-end / ...)
- [ ] I have updated the README and other relevant documents (guides...)
- [ ] I have added sufficient documentation both in code, as well as in the READMEs

2023-06-07 14:29 UTC, RezaRahemtola requested changes
Also add a README to specify how to generate the key / cert files as you specified that users should replace it with their own

2023-06-07 14:29 UTC, RezaRahemtola commented on vault/Dockerfile
> +COPY cert.pem /vault/certs/
Since you already specified a workdir, you can use relative paths here, it will be cleaner (and can also an easier change of workdir :wink: )

2023-06-07 14:29 UTC, RezaRahemtola commented on vault/Dockerfile
> +    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main" | tee /etc/apt/sources.list.d/hashicorp.li
Could be great to add a comment with some explanations of what this does (or a link to the documentation ?)

2023-06-07 14:54 UTC, adamdeziri commented on vault/Dockerfile
> +COPY cert.pem /vault/certs/
Done :)

2023-06-07 14:54 UTC, adamdeziri commented on vault/Dockerfile
> +    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com focal main" | tee /etc/apt/sources.list.d/hashicorp.li
Done :)

2023-06-09 16:15 UTC, RezaRahemtola approved these changes

2023-06-09 16:15 UTC, merged